apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-go-v2
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: service-go
        version: v2
    spec:
      restartPolicy: Always
      containers:
      - name: service-go
        image: registry.cn-shanghai.aliyuncs.com/istio-test/service-go:v2
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /env
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /env
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 3
