apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-test-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "istio-test.will"
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-test
spec:
  hosts:
  - "istio-test.will"
  gateways:
  - istio-test-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: service-js
    - uri:
        prefix: /env
    route:
    - destination:
        host: service-python