# 超时
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: service-python-timeout
spec:
  destination:
    name: service-python
  route:
  - labels:
      version: v2
    weight: 50
  - labels:
      version: v1
    weight: 50
  httpReqTimeout:
    simpleTimeout:
      timeout: 1s