# 根据自定义请求头配置路由
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: service-python-react
spec:
  destination:
    name: service-python
  match:
    request:
      headers:
        app-client:
          regex: "react"
  precedence: 1
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: service-python-vue
spec:
  destination:
    name: service-python
  match:
    request:
      headers:
        app-client:
          regex: "vue"
  precedence: 1
  route:
  - labels:
      version: v2