# 熔断器
apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: service-go-cb
spec:
  destination:
    name: service-go
    labels:
      version: v1
  circuitBreaker:
    simpleCb:
      maxConnections: 1
      sleepWindow: 1s
      httpDetectionInterval: 1s