# 根据请求头配置路由
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: service-js-react
spec:
  destination:
    name: service-js
  match:
    request:
      headers:
        user-agent:
          regex: ".*?(Chrome).*?"
  precedence: 2
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: service-js-vue
spec:
  destination:
    name: service-js
  match:
    request:
      headers:
        user-agent:
          regex: ".*?(Firefox).*?"
  precedence: 2
  route:
  - labels:
      version: v2