# 故障注入abort
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: service-go-abort
spec:
  destination:
    name: service-go
  route:
  - labels:
      version: v2
    weight: 50
  - labels:
      version: v1
    weight: 50
  httpFault:
    abort:
      percent: 75
      httpStatus: 500
