# 根据源服务配置路由
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: service-go-react
spec:
  destination:
    name: service-go
  match:
    source:
      name: service-python
      labels:
        version: v1
  precedence: 1
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: service-go-vue
spec:
  destination:
    name: service-go
  match:
    source:
      name: service-python
      labels:
        version: v2
  precedence: 1
  route:
  - labels:
      version: v2