# python流量路由到v1版本
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: service-python-default
spec:
  destination:
    name: service-python
  precedence: 1
  route:
  - labels:
      version: v1