# 流量拆分
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: service-go-v1-v2
spec:
  destination:
    name: service-go
  route:
  - labels:
      version: v1
    weight: 25
  - labels:
      version: v2
    weight: 75