# 故障注入delay
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: service-go-delay
spec:
  destination:
    name: service-go
  route:
  - labels:
      version: v1
  httpFault:
    delay:
      fixedDelay: 1.000s
      percent: 100

  