# 根据源服务配置路由
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: service-go-v1-via-service-node-v1
spec:
  destination:
    name: service-go
  match:
    source:
      name: service-node
      labels:
        version: v1
  precedence: 1
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: service-go-v2-via-service-node-v2
spec:
  destination:
    name: service-go
  match:
    source:
      name: service-node
      labels:
        version: v2
  precedence: 1
  route:
  - labels:
      version: v2