# 故障注入delay
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: service-go-delay
spec:
  destination:
    name: service-go
  route:
  - labels:
      version: v2
    weight: 50
  - labels:
      version: v1
    weight: 50
  httpFault:
    delay:
      fixedDelay: 2.000s
      percent: 50
